#!/bin/sh
#This is a general installer for Arch Linux that installs and confiures Arch Utilities for Luke Bubar

t=$TERMINAL
n="
"
# Updater
#$t sudo pacman -Syu
sudo pacman -Syu

# Main installer

# Core Utils

# This is an array of all the programs we need to install (or check to see if they are installed).
core=(
"gvim"
"neovim"
"riot-desktop"
"fish"
"youtube-dl"
"st"
"xwallpaper"
"surf"
"dmenu"
"ls"
"zathura"
"syncthing"
"firefox"
)

core_extra=(
"openscad"
"gnome-maps"
"youtube-viewer"
)

gaming=(
"lutris"
"steam"
"discord"
)

all=(
"core"
"core_extra"
"gaming"
)

# query

#for j in ${all[@]}
#do
#	read -p "Do you want to install the $j list? ( 'y' for yes, 'n' for no, or 'l' for list the programs) $n " ynl
#	case $ynl in
#		[Yy]* ) progs=${$j[@]};;
#		[Nn]* ) ;;
#		[Ll]* ) echo ${$j[@]};;
#		* ) echo "Please pick yes, no, or list.$n";;
#	esac

progs=${core[@]} #temporary patch until I can get the query workin

for i in ${progs[@]}
do
	#$t sudo pacman -S --noconfirm --needed $i
	sudo pacman -S --needed $i
done
#done

# BlackArch

# Insert query of whether or not you would like to install blackarch above
cd ~/Downloads
curl -O https://blackarch.org/strap.sh
sha1sum strap.sh
chmod +x strap.sh
sudo ./strap.sh
cd ~/
